#!/bin/sh
cd /opt/dwarf-fortress
# export SDL_DISABLE_LOCK_KEYS=1 # Work around for bug in Debian/Ubuntu SDL patch.
#export SDL_VIDEO_CENTERED=1    # Centre the screen.  Messes up resizing.

umask 0002 # Make sure that any saves created get 775/664
if [ -e /lib32/libz.so.1 ]; then 
	export LD_PRELOAD=/lib32/libz.so.1
fi
exec ./libs/Dwarf_Fortress "$@"

